@echo off
echo Starting FlightRosterIQ Backend Server...
cd backend
start "FlightRosterIQ Backend" cmd /k "node server.js"
echo Backend server starting on port 8080...
echo.
echo Press any key to return...
pause >nul
